name: 'publish containers'
on:
  push:
    branches:
      - master

# https://github.com/redhat-actions/push-to-registry/blob/main/.github/workflows/ghcr-push.yaml
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAGS: v1 ${{ github.sha }}

jobs:
  push-ghcr:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: install podman
      #   run: |
      #     sudo apt-get -y update && \
      #     sudo apt-get -y install podman

      - name: build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: server
          tags: latest ${{ env.IMAGE_TAGS }}
          containerfiles: |
            server/Containerfile

      # # https://github.com/redhat-actions/podman-login
      # - name: login to ghcr
      #   uses: redhat-actions/podman-login@v1
      #   with:
      #     username: ${{ env.REGISTRY_USER }}
      #     password: ${{ env.REGISTRY_PASSWORD }}
      #     registry: ${{ env.IMAGE_REGISTRY }}

      - name: push to ghcr
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
